version: "1.0"
services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3026:3026"
    environment: 
      # STATIC ACCOUNT SWAGGER  
      PORT: ${DB_HOST}